version: '3.4'

services:
  mgdockerblazorapp:
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "80:8080"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  postgres:
    restart: always
    image: postgres:14-alpine
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'MGDatabase'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'